// Top-level build file for multi-module project.

// Define common properties for all subprojects
ext {
    minecraft_version = "1.20.1"
    yarn_mappings = "1.20.1+build.10"
    loader_version = "0.15.7"
    mod_version = "1.1-1.20.1"
    maven_group = "net.thesquire"
    archives_base_name = "dimensionalweather"
    fabric_version = "0.92.2+1.20.1"
    forge_version = "47.4.10"
}

// Set the group and version for the entire project
group = ext.maven_group
version = ext.mod_version

allprojects {
    repositories {
        // Common repositories for all subprojects
        mavenCentral()
        // Add any other common repositories here if needed
    }
}

subprojects {
    apply plugin: 'java' // Apply java plugin to all subprojects

    // Configure Java version for all subprojects
    def targetJavaVersion = 17
    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = "UTF-8"
        if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
            it.options.release = targetJavaVersion
        }
    }

    java {
        def javaVersion = JavaVersion.toVersion(targetJavaVersion)
        if (JavaVersion.current() < javaVersion) {
            toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
        // archivesBaseName will be set in specific subproject build.gradle files
    }
}